### ISSUE TITLE
Double negation bug

### ISSUE THREAD

**Issue by scottmangiapane** [mrieppel/TruthTableGenerator#1]
Double negation results in an error message saying that the input is invalid.

Ex:
&nbsp;&nbsp;&nbsp;&nbsp;AvB works
&nbsp;&nbsp;&nbsp;&nbsp;~(AvB) works
&nbsp;&nbsp;&nbsp;&nbsp;~(~(AvB)) doesn't work

**Comment by mrieppel** [comment]
Thanks!  But that's just the syntax I'm using for propositional logic.  The grammar is:

p ::=  Atomic | ~p | (p & p) | (p v p) | (p > p) | (p <> p)

Negation doesn't introduce parentheses, so the double negation of (AvB) would be ~~(AvB), just like the double negation of P would be ~~P, rather than ~(~(P)).

**Comment by scottmangiapane** [comment]
Oh okay, I see what you mean. My original though process was that (A NAND
B) NAND C could only be written as ~(~(A&B)&C) (and therefore cause the
parenthesis problem), because I didn't know that Sheffer stroke was the
same thing as NAND and I can just use that instead.

Also, great website! I particularly like the conversion to LaTeX table.

**Comment by mrieppel** [comment]
Cool, happy to hear you like the program!  The double-NAND formula you have ~(~(A&B)&C) is well formed as it stands.  It would only be ill-formed if you didn't have the second conjunct, as in ~(~(A&B)).
